version: "3.7"

services:
  fhir-server:
    container_name: fhir-server
    image: "samply/blaze:0.19"
    environment:
      BASE_URL: "http://fhir-server:8080"
      JAVA_TOOL_OPTIONS: "-Xmx4g"
      LOG_LEVEL: debug
    ports:
      - ${PORT_BLAZE_FHIR:-127.0.0.1:8080}:8080
    volumes:
      - "blaze-data:/app/data"

volumes:
  blaze-data:
